@file:OptIn(ExperimentalTime::class)

package com.eventslooped.klokka

import kotlinx.serialization.KSerializer
import kotlinx.serialization.serializer
import kotlin.jvm.JvmInline
import kotlin.time.ExperimentalTime

/** Opaque identifier of a single job run. Generated by the [com.eventslooped.klokka.spi.JobStore]. */
@JvmInline
public value class JobId(public val value: String)

/**
 * Name of a queue. Workers drain queues in the order they are declared:
 * declared order is priority. There are no per-job priority numbers.
 */
@JvmInline
public value class QueueName(public val value: String) {
    public companion object {
        public val DEFAULT: QueueName = QueueName("default")
    }
}

/** Identifies a worker instance for lease ownership. Stable for the lifetime of one runtime. */
@JvmInline
public value class WorkerId(public val value: String)

/**
 * A registered job type: a stable string [kind] plus the payload [serializer].
 *
 * The [kind] is the durable identity of the job. It is stored in the database and must
 * survive class renames, package moves, and rolling deploys. Never derive it from a
 * class or function name. Allowed characters: lowercase letters, digits, '-', '.', max 128 chars.
 */
public class JobType<T>(
    public val kind: String,
    public val serializer: KSerializer<T>,
) {
    init {
        require(kind.isNotEmpty() && kind.length <= 128 && kind.all { it.isLowerCase() || it.isDigit() || it == '-' || it == '.' }) {
            "Job kind must be 1..128 chars of lowercase letters, digits, '-' or '.': was '$kind'"
        }
    }

    override fun toString(): String = "JobType($kind)"
}

/** Creates a [JobType] for a @Serializable payload type. */
public inline fun <reified T> jobType(kind: String): JobType<T> = JobType(kind, serializer())

/**
 * Per-enqueue options. All fields have defaults so the simple path stays one argument shorter.
 *
 * [uniqueKey] enables store-enforced deduplication: enqueueing a second job with the same
 * key while the first is not yet in a terminal state is an idempotent no-op that returns
 * the existing job's id.
 *
 * [retry] overrides the runtime's default retry policy for this job only. Null means default.
 */
public data class JobOptions(
    val queue: QueueName = QueueName.DEFAULT,
    val uniqueKey: String? = null,
    val retry: RetryPolicy? = null,
)

/** Builder-style factory so call sites read as `options { uniqueKey = "receipt-42" }`. */
public fun options(build: JobOptionsBuilder.() -> Unit): JobOptions = JobOptionsBuilder().apply(build).build()

public class JobOptionsBuilder {
    public var queue: QueueName = QueueName.DEFAULT
    public var uniqueKey: String? = null
    public var retry: RetryPolicy? = null

    public fun build(): JobOptions = JobOptions(queue = queue, uniqueKey = uniqueKey, retry = retry)
}

/** Continuation trigger conditions for [continueWith]-style chaining. */
public enum class Outcome {
    Succeeded,
    DeadLettered,
    AnyTerminal,
}
