@file:OptIn(ExperimentalTime::class)

package com.eventslooped.klokka

import kotlinx.serialization.KSerializer
import kotlinx.serialization.serializer
import kotlin.jvm.JvmInline
import kotlin.random.Random
import kotlin.time.ExperimentalTime

/** Opaque identifier of a single job run. Generated by the [com.eventslooped.klokka.spi.JobStore]. */
@JvmInline
public value class JobId(public val value: String)

/**
 * Name of a queue. Workers drain queues in the order they are declared:
 * declared order is priority. There are no per-job priority numbers.
 */
@JvmInline
public value class QueueName(public val value: String) {
    public companion object {
        public val DEFAULT: QueueName = QueueName("default")
    }
}

/** Identifies a worker instance for lease ownership. Stable for the lifetime of one runtime. */
@JvmInline
public value class WorkerId(public val value: String) {
    public companion object {
        /**
         * A fresh random id of the form `worker-<hex>`. This is the default when no stable
         * identity (hostname, pod name) is configured; a new one is drawn per call.
         */
        public fun random(): WorkerId = WorkerId("worker-" + Random.nextLong().toULong().toString(16))
    }
}

/**
 * A registered job type: a stable string [kind], the payload [serializer], and the [queue]
 * its jobs go to unless an enqueue call overrides it.
 *
 * The [kind] is the durable identity of the job. It is stored in the database and must
 * survive class renames, package moves, and rolling deploys. Never derive it from a
 * class or function name. Allowed characters: lowercase letters, digits, '-', '.', max 128 chars.
 *
 * The [queue] is a routing default, not identity. It lives on the descriptor because the
 * producer writes the queue onto the job row, and the descriptor is the one object producer
 * and worker code share; handler registration never names a queue. Changing it is a
 * producer redeploy: drain both the old and the new queue during the rollout.
 */
public class JobType<T>(
    public val kind: String,
    public val serializer: KSerializer<T>,
    public val queue: QueueName = QueueName.DEFAULT,
) {
    init {
        require(kind.isNotEmpty() && kind.length <= 128 && kind.all { it.isLowerCase() || it.isDigit() || it == '-' || it == '.' }) {
            "Job kind must be 1..128 chars of lowercase letters, digits, '-' or '.': was '$kind'"
        }
    }

    override fun toString(): String = "JobType($kind)"
}

/** Creates a [JobType] for a @Serializable payload type; [queue] is the default queue for its jobs. */
public inline fun <reified T> jobType(kind: String, queue: QueueName = QueueName.DEFAULT): JobType<T> =
    JobType(kind, serializer(), queue)

/**
 * Per-enqueue options. All fields have defaults so the simple path stays one argument shorter.
 *
 * [queue] overrides [JobType.queue] for this one job; null, the default, means "use the
 * type's queue". Set it only when a specific job must go somewhere other than where its
 * kind normally goes.
 *
 * [uniqueKey] enables store-enforced deduplication: enqueueing a second job with the same
 * key while the first is not yet in a terminal state is an idempotent no-op that returns
 * the existing job's id.
 *
 * Only persistable data belongs here. Retry policies are functions and cannot be
 * persisted, so retry overrides live at handler REGISTRATION (per kind, code-defined,
 * identical on every node), never per enqueue.
 */
public data class JobOptions(
    val queue: QueueName? = null,
    val uniqueKey: String? = null,
)

/** Builder-style factory so call sites read as `options { uniqueKey = "receipt-42" }`. */
public fun options(build: JobOptionsBuilder.() -> Unit): JobOptions = JobOptionsBuilder().apply(build).build()

public class JobOptionsBuilder {
    public var queue: QueueName? = null
    public var uniqueKey: String? = null

    public fun build(): JobOptions = JobOptions(queue = queue, uniqueKey = uniqueKey)
}

/** Continuation trigger conditions for [continueWith]-style chaining. */
public enum class Outcome {
    Succeeded,
    DeadLettered,
    AnyTerminal,
}
